### ISSUE TITLE
Missing tables in SQLite

### ISSUE THREAD

**Issue by erhuz** [laykith/fake-news#2]
Error message:
```
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: posts in  /Users/erhuz/Sites/sandbox/fake-news/vendor/laykith/easyconnect/src/EasyConnect.php:77  
Stack trace: #0 /Users/erhuz/Sites/sandbox/fake-news/vendor/laykith/easyconnect/src/EasyConnect.php(77):  
PDO->prepare('SELECT posts.id...') #1 /Users/erhuz/Sites/sandbox/fake-news/index.php(19): EasyConnect\EasyConnect->getData('SELECT posts.id...') #2 {main}  
thrown in /Users/erhuz/Sites/sandbox/fake-news/vendor/laykith/easyconnect/src/EasyConnect.php on line 77
```

**Comment by brooman** [comment]
https://github.com/laykith/fake-news/pull/3
